### ISSUE TITLE
Utilizing a new community fork of Dragonfly

### ISSUE THREAD

**Issue by LexiconCode** [chaosparrot/parrot.py#1]
Greetings, I noticed you were using older fork of dragonfly. Over the past year and a half the community has banded together in the [Dictation Toolbox Org](https://github.com/dictation-toolbox) to create an active fork of [Dragonfly](https://github.com/dictation-toolbox/dragonfly).

The community has fixed many of the outstanding bugs in the original dragonfly. It supports Python 3 and alternate speech recognition engines such as Kaldi and CMU Pocket Sphinx maintaining backwards compatibility for older dragonfly grammars. In addition the fork also developing cross-platform support Windows, Mac (WIP), and Linux (WIP). 

To install simply `pip install dragonfly2`

There's an active community in [Gitter Chat](https://gitter.im/dictation-toolbox/dragonfly) that can provide support and would love to hear about your work with parrot.py

**Comment by chaosparrot** [comment]
Hey, thanks for reaching out! I'll check out the updated fork :) That will probably improve the installation process as well if it stays backwards compatible!

**Comment by chaosparrot** [comment]
I tested the dragonfly2 fork briefly, and it seems to work. So I updated the installation and readme docs to point to the latest version. Thanks again!

**Comment by LexiconCode** [comment]
You're welcome, Thanks for your work with Parrot.py.
