### ISSUE TITLE
Comparison.wav file not always same length as recording

### ISSUE THREAD

**Issue by chaosparrot** [chaosparrot/parrot.py#50]
According to users, the comparison wav files are about twice the size than the source recordings. This seems to happen on macOS 14.4, so I might be able to debug it some time.

**Comment by templateK** [comment]
I have same problem in macOS 10.14.5(mojave).  Comparison wave file size always ends up with following size.

`comparison wave file size` = `source wave file size * 2 + 44` in bytes

I don't know if it's normal but the content of the comparison.wav is nonsensical and If I try to execute `learning the data`,
it crashes with `Job 1, 'python settings.py' terminated by signal SIGSEGV (Address boundary error)`

<br>

Waveform of tongue clucks (4 minutes)
![parrot_recording_zoom_out](https://github.com/chaosparrot/parrot.py/assets/3207776/3577569f-2d05-4cbc-a344-152e5d22c455)

First 2 seconds of the waveform
![parrot_recording_zoom_in](https://github.com/chaosparrot/parrot.py/assets/3207776/f91e3644-32cf-4bfe-962e-cb11f3c97e05)
